### ISSUE TITLE
dead code elimination

### ISSUE THREAD

**Issue by ReiquelApplegate** [ZeldaClassic/ZeldaClassic#13]
For example, in qst.cpp there is:

`int32_t memDBGwatch[8]= {0,0,0,0,0,0,0,0}; //So I can monitor memory crap`

which is not used by anything.  Still compiles after deleting that line.

**Comment by ZelRai** [comment]
I don't see a reason to keep this either. What good does intializing an empty array do for Debugging?

**Comment by ReiquelApplegate** [comment]
removed that array in https://github.com/ZeldaClassic/ZeldaClassic/commit/50fb0462f1e9068bea26a913a526d436f5316cd0
