### ISSUE TITLE
typos in credits

### ISSUE THREAD

**Issue by jeffythedragonslayer** [ZeldaClassic/ZeldaClassic#5]
In zc/ending.cpp we have:

```
	const EndingTextLine credits[]=
	{
		{ "CREDITS", 64, 768, red			},
		{ "ZC Development Members Past and Present",   72, 816, white },
		{ "Phantom Mance",    76, 832, white },
	};
```

"Members" is plural, but only Phantom Menace is mentioned, misspelled.

**Comment by ZelRai** [comment]
Fixed typo, we can try adding the full list once we can verify scrolling is not broken. (Shouldn't be.)
